version: 2.1

references:
  go-machine-image: &go_machine_image
    circleci/classic:201808-01

  # common references
  common_envs: &common_envs
    BRANCH: "main-nROX4fWS"

executors:
  go:
    working_directory: /blah/main-nROX4fWS
    docker:
      - image: golang:1.14.6
    environment:
      <<: *common_envs
      GOPATH: /go
